die_roll/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)


author = 'Your name here'

doc = """
copy of Gahana experiment
"""

LEFT_RIGHT_CHOICES = [
    ('1', ''),
    ('2', ''),
    ('3', ''),
    ('4', ''),
    ('5', ''),
    ('6', ''),
    ('7', ''),
    ('8', ''),
    ('9', ''),
]

class Constants(BaseConstants):
    name_in_url = 'questionnaire'
    players_per_group = None
    num_rounds = 1
    show_app_name = "die_roll"
    die_conversion = c(0.2)


    cheat_tax_choices = tuple([('0', "Always justified")] + LEFT_RIGHT_CHOICES + [('10', "Never justified")])

    tax_democracy_choices = tuple([('0', "Absolutely essential")] + LEFT_RIGHT_CHOICES + [('10', "Not essential")])

class Subsession(BaseSubsession):
    pass

class Group(BaseGroup):
    pass

class Player(BasePlayer):
    die_roll = models.IntegerField(min = 0, max = 6, label="Please enter the number of the dice")
    virtual_dice = models.IntegerField()
    
    def set_payoff(self):
        self.payoff = self.die_roll * Constants.die_conversion
        self.participant.vars['module2_payoff'] = self.payoff

die_roll/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

die_roll/templates/die_roll/Dice.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Module 2 - payment
{% endblock %}

{% block content %}

Now please roll your dice on your table once and enter the number that you roll. The number will be multiplied by <b>{{ Constants.die_conversion }}</b> to get your payment for the module.

{% formfield player.die_roll label=""%}

    {% next_button %}

{% endblock %}

die_roll/templates/die_roll/DiceRolling.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}
{% block title %}
    module 2 Dice Rolling
{% endblock %}

{% block content %}
    <div class="demo">
        <div class="wrap">
            <div id="dice" class="dice dice_t"></div>
        </div>
        <p id="result">Please roll the die!</p>
    </div>
    {% formfield player.die_roll %}


    <input type="hidden" name="virtual_dice" id="id_virtual_dice"  >


    {% next_button %}

    <ol type="a" class="list-group">

        <li class="list-group-item">
            There is a virtual die.
        </li>
    </ol>
{% endblock %}


{% block scripts %}
    {#    ORIGINAL CODE FOR DICE ROLLING IS TAKEN FROM HERE: http://www.goocode.net/js/51-jquery-dice-animation.html #}
    <script>
        $(function () {
            var dice = $("#dice");

            dice.click(function () {
                $(".wrap").append("<div id='dice_mask'></div>");//add mask
                dice.attr("class", "dice");//After clearing the last points animation
                dice.css('cursor', 'default');
                var num = Math.floor(Math.random() * 6 + 1);//random num 1-6
                $('#id_virtual_dice').val(num);//record dice
                $('#id_virtual_dice').attr('value', num);
                dice.animate({left: '+2px'}, 100, function () {
                    dice.addClass("dice_t");
                }).delay(200).animate({top: '-2px'}, 100, function () {
                    dice.removeClass("dice_t").addClass("dice_s");
                }).delay(200).animate({opacity: 'show'}, 600, function () {
                    dice.removeClass("dice_s").addClass("dice_e");
                }).delay(100).animate({left: '-2px', top: '2px'}, 100, function () {
                    dice.removeClass("dice_e").addClass("dice_" + num);
                    $("#result").html("The number is:<span>" + num + "</span>");
                    dice.css('cursor', 'pointer');
                    $("#dice_mask").remove();//remove mask
                });
            });
        });
    </script>

{% endblock %}


{% block styles %}
    <style>
        .wrap {
            width: 90px;
            height: 90px;
            margin: 120px auto 30px auto;
            position: relative
        }

        .dice {
            width: 90px;
            height: 90px;
            background: url({% static "spanish_die_game/imgs/dice.png" %}) no-repeat;
        }

        .dice_1 {
            background-position: -5px -4px
        }

        .dice_2 {
            background-position: -5px -107px
        }

        .dice_3 {
            background-position: -5px -212px
        }

        .dice_4 {
            background-position: -5px -317px
        }

        .dice_5 {
            background-position: -5px -427px
        }

        .dice_6 {
            background-position: -5px -535px
        }

        .dice_t {
            background-position: -5px -651px
        }

        .dice_s {
            background-position: -5px -763px
        }

        .dice_e {
            background-position: -5px -876px
        }

        p#result {
            text-align: center;
            font-size: 16px;
            font-weight: 600;
        }

        p#result span {
            font-weight: bold;
            color: #f30;
            margin: 6px
        }

        #dice_mask {
            width: 90px;
            height: 90px;
            background: #fff;
            opacity: 0;
            position: absolute;
            top: 0;
            left: 0;
            z-index: 999
        }

        #id_virtual_dice {
            display: none
        }
    </style>

{% endblock %}

die_roll/templates/die_roll/Instructions.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Module 2 - Instructions
{% endblock %}

{% block content %}
<ul>
  <li class="list-group-item">
    There is a virutal dice. We will ask you to roll the die once. You
    will be paid according to whichever number is facing upwards after your
    first roll. Each dot on the upwards facing side of the die is
    worth {{ Constants.die_conversion}}.
  </li>
  <li class="list-group-item">
    So if you roll a 4, you will be paid {{example_4}} and if you roll
    a 1, you will be paid {{example_1}}
  </li>
</ul>
    {% next_button %}

{% endblock %}

die_roll/templates/die_roll/MyPage.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Page title
{% endblock %}

{% block content %}

    {% next_button %}

{% endblock %}

die_roll/templates/die_roll/Questionnaire.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Questionnaire
{% endblock %}

{% block content %}
{% for field in form %} {% formfield field %}
{% endfor %}

    {% next_button %}

{% endblock %}

die_roll/templates/die_roll/Results.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    End of module 1
{% endblock %}

{% block content %}
    This is the end of module 1
    {% next_button %}
{% endblock %}

